services:
  - type: web
    name: htoo-web
    env: docker
    buildCommand: composer install
    dockerfilePath: Dockerfile
    plan: free
    branch: main
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000