services:
  - type: web
    name: htooautomobileservice
    env: docker
    region: oregon
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_NAME
        value: Laravel
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
      - key: NODE_VERSION
        value: 18.x
