services:
  - type: web
    name: laravel-vue-sqlite
    env: docker
    runtime: php
    plan: free
    region: oregon
    envVars:
      - key: APP_NAME
        value: Laravel
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: sqlite
      - key: NODE_VERSION
        value: 18.x
    healthCheckPath: /
    autoDeploy: true