services:
  - type: web
    name: laravel-vue-sqlite
    env: native
    plan: free
    branch: main
    autoDeploy: true
    startCommand: php artisan serve --host 0.0.0.0 --port 80services:
  - type: web
    name: laravel-vue-sqlite
    env: native
    buildCommand: |
      composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
      npm ci
      npm run build
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: APP_NAME
        value: Laravel
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          type: web
          name: laravel-vue-sqlite
          property: host
      - key: DB_CONNECTION
        value: sqlite