name: Deploy Laravel Application

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4.6' # သင့် local/server က PHP version ပြောင်းပေးပါ

      - name: Install Composer Dependencies
        run: |
          composer install --no-dev --optimize-autoloader --ignore-platform-reqs --no-scripts

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '26' # သင့် local က node version နဲ့ ကိုက်ညီတာ ထားပါ

      - name: Install NPM & Build Production Assets
        run: |
          npm install
          npm run build

      - name: Copy Build Assets to EC2 via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'public/build/'
          target: '/var/www/htoo/'

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/htoo

            sudo chown -R $USER:$USER storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache

            # 1. Server ပေါ်က Local changes တွေကို ဖယ်ပြီး Code အသစ်ဆွဲမယ်
            git fetch --all
            git reset --hard origin/main

            # 2. PHP Dependencies သွင်းမယ်
            composer install --no-dev --optimize-autoloader --ignore-platform-reqs
            # npm install
            # npm run build

            # 3. Laravel Optimization & Permissions
            php artisan optimize:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            # php artisan migrate:fresh --seed --force
            # sudo systemctl reload nginx

            sudo chown -R www-data:www-data storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache
